### ISSUE TITLE
Narrow results down per pages

### ISSUE THREAD

**Issue by klarasch** [igoradamenko/figma-search-extension#1]
Hi, continuing on the feedback from the Chrome Store :)

To me, it would be extremely helpful if the search could be narrowed down to just current page instead of searching the whole file or, alternatively, if the search results could show the name of the page the result is placed in.

Here's a very simple demo: consider "Rectangle 1" placed in Page 1 and Page 2. Currently, the search results look like this:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/17709591/115386716-085a2500-a1da-11eb-80dd-5f18e0eb4123.png">

while it would be really helpful in our workflow to know to what page do the rectangles belong. (The in-one-minute-made demo file is here https://www.figma.com/file/mo3i53odLGv2zs5SKeAfWZ/Chrome-extension-demo?node-id=1%3A3) 

Real-life need comes from the fact we're giving IDs both to pages and components and our developers have their documentation organised accordingly – and sometimes their being navigated to "element of some ID on page of some ID" and if they now search for the ID with your extension, they get all layers with the ID but don't see their page context, so they need to click through them all (we are now avoiding that by putting the page ID to layer names directly, too, but better solution would be what I'm describing).

Hope it makes sense now and once more thank you so much for this life-saving extension!

**Comment by klarasch** [comment]
Or, generally at least the first two levels of path (Page and the first-level frame) of the element would be great great great, but that is the extension already ☺️

**Comment by igoradamenko** [comment]
Hey! Thank you for the detailed explanation. We will try to do something with it 🐨

**Comment by klarasch** [comment]
Thanks so much. Looking forward!

**Comment by igoradamenko** [comment]
Hey there!

Small update about this issue:

1. We've implemented breadcrumbs in search results: #2.
2. Also we've added pages filter: #3.

Those changes has been already released in Mozilla Add-ons and are currently waiting for review in Chrome Web Store.

But now we've found some issues that will be resolved as soon as possible. They're not bugs, rather “inconsistency issues”. E.g. “Current page” tab won't be updated when you reopen extension after page switch, or “Not found” errors know nothing about page filter.

As I said, those issues will be fixed soon. For now I guess it's fine to close this issue. Feel free to reopen it if you have any questions 🐨

**Comment by klarasch** [comment]
Hi Igor, thank you so much, that is absolutely amazing! 😍 I truly appreciate your work and looking forward to trying it out once it arrives to Chrome. Cheers! ✨👏❤️
